# Container Versions stored in '.env'
---
version: '3'
services:
    init:
        build: ./init
        container_name: releng-init
        environment:
            - GLOBAL_JJB_VERSION=v0.10.2
        volumes:
            - init:/init/
            - jenkins:/jenkins
        links:
            - jenkins
            - gerrit
            - nexus
    ldap:
        image: "osixia/openldap:$OPENLDAP_CONTAINER_VERSION"
        container_name: releng-ldap
        env_file: config.env
        command: "--loglevel debug --copy-service"
        volumes:
            - ./ldap/bootstrap/groups.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-groups.ldif
        ports:
            - "636:636"
    jenkins:
        build:
            context: ./jenkins
            args:
                - JENKINS_VERSION=$JENKINS_CONTAINER_VERSION
        container_name: releng-jenkins
        env_file: config.env
        environment:
            - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
            - VIRTUAL_HOST=jenkins.localhost
            - VIRTUAL_PORT=8080
        volumes:
            - jenkins:/var/jenkins_home
        expose:
            - "8080"
        depends_on:
            - ldap
            - nginx
        links:
            - ldap
            - nginx
    jenkins-agent:
        build: ./jenkins/agent
        container_name: releng-agent
        env_file: config.env
        ports:
            - "22"
        links:
            - "nginx:jenkins.localhost"
            - "nginx:nexus.localhost"
            - "nginx:gerrit.localhost"
    gerrit:
        image: "openfrontier/gerrit:$GERRIT_CONTAINER_VERSION"
        container_name: releng-gerrit
        env_file: config.env
        environment:
            - VIRTUAL_HOST=gerrit.localhost
            - VIRTUAL_PORT=8080
        volumes:
            - gerrit:/var/gerrit/review_site
        expose:
            - "8080"
        ports:
            - "29418:29418"
        depends_on:
            - ldap
            - nginx
        links:
            - ldap
            - nginx
    nexus:
        image: "sonatype/nexus:$NEXUS_CONTAINER_VERSION"
        container_name: releng-nexus
        env_file: config.env
        environment:
            - VIRTUAL_HOST=nexus.localhost
            - VIRTUAL_PORT=8081
        volumes:
            - nexus:/sonatype-work
        expose:
            - "8081"
        depends_on:
            - nginx
        links:
            - nginx
    postgres:
        image: postgres:latest
        env_file: config.env
        expose:
            - "5432"
    nginx:
        image: jwilder/nginx-proxy:latest
        container_name: releng-ingress
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
    jenkins:
    gerrit:
    nexus:
    init:
