---
version: '3'
services:
    init:
        build: ./init
        container_name: releng-init
        volumes:
            - init:/init/
            - jenkins:/jenkins
        links:
            - jenkins
            - gerrit
    ldap:
        image: osixia/openldap:latest
        container_name: releng-ldap
        env_file: config.env
        command: "--loglevel debug --copy-service"
        volumes:
            - ./config/ldap/bootstrap/groups.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-groups.ldif
        ports:
            - "636:636"
    jenkins:
        build: ./jenkins
        container_name: releng-jenkins
        env_file: config.env
        environment:
            - VIRTUAL_HOST=jenkins.localhost
            - VIRTUAL_PORT=8080
        volumes:
            - jenkins:/var/jenkins_home
        expose:
            - "8080"
        depends_on:
            - ldap
            - nginx
        links:
            - ldap
            - nginx
            - jenkins-agent
    jenkins-agent:
        build: ./jenkins/agent
        container_name: releng-agent
        ports:
            - "22"
        environment:
            - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUX11sDBXacCE/LBdcXO4E27OZbWtjNadXPGIRTN1leUFWJlnljlZT31Wbml8fvp+5BKbVRHP/W9IWj/PlBTxrxOPMN2Rch40tarPU1PxWJYM203n6Ac+GWKcfSPiikmfXiJ+pJHs+0E1MVhpLe08pb3qVdvwAGdQXVC53dg9ebrb5KirbLvWdEMewfVlxdB2ru2p358QN5Y7HHsAqW1sMr18G1/O5bVJl7g1JbnQ+/YjVaJRo7cDuonTOeatlEMfZZXzlermgXCcVFSIo/oKuKbtilZ2ye17ax9kN4rfVAAXIeOAUZWeCad32EdQEO7xL956ZftXyV+jlw03CndD5
    gerrit:
        image: openfrontier/gerrit:latest
        container_name: releng-gerrit
        env_file: config.env
        environment:
            - VIRTUAL_HOST=gerrit.localhost
            - VIRTUAL_PORT=8080
        volumes:
            - gerrit:/var/gerrit/review_site
        expose:
            - "8080"
        ports:
            - "29418:29418"
        depends_on:
            - ldap
            - nginx
        links:
            - ldap
            - nginx
    postgres:
        image: postgres:latest
        env_file: config.env
        expose:
            - "5432"
    nginx:
        image: jwilder/nginx-proxy:latest
        restart: always
        container_name: releng-ingress
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
    jenkins:
    gerrit:
    init:
